version: '3.7'

services:
  php:
    build: './php'
    networks:
      - backend
    volumes:
      - ./www:/var/www/html
    container_name: php
  apache:
    build: './apache'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
    container_name: apache
  mysql:
    image: mariadb:10.7.3
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=dkfmadl
    container_name: mysql

networks:
  frontend:
  backend:
    